### ISSUE TITLE
Paper Model Weights

### ISSUE THREAD

**Issue by gjustin40** [jiankang1991/TGRS_DisOptNet#3]
I really appreciate you providing the code. It has been very helpful for my research. @jiankang1991

I was wondering if it would be possible to get the weight that produce the scores mentioned in the paper.
I have tried several times using the provided code, but I have not been able to reach the scores mentioned in the paper.
If it is not a problem, could I receive the weight? 

Thank you.

**Comment by jiankang1991** [comment]
@gjustin40 Thank you for the interest of the work. I have already uploaded the weights to Google Drive. Please kindly find them in the updated README.
